@localhost=locahost:4004/odata/v4/main
@id=2194cd81-5598-4af6-9c59-4e378629b139


GET http://localhost:4004/odata/v4/main/Customers
Content-Type: application/json

###


POST http://localhost:4004/odata/v4/main/Customers
Content-Type: application/json

{
    "id": "{{id}}",
    "firstName": "Jonatas",
    "lastName": "Cardoso",
    "email": "jonatasmedeiros@gmail.com"
}

###

DELETE  http://localhost:4004/odata/v4/main/Customers(id={{id}}
Content-Type: application/json


###

PATCH  http://localhost:4004/odata/v4/main/Customers(id={{id}})
Content-Type: application/json

{
    "firstName": "John"
}

###


# Ordenando dados com $orderby

GET http://localhost:4004/odata/v4/main/Customers?$orderby=firstName desc,lastName desc
Content-Type: application/json
